url = "http://groovyando.org"
name = "GrailsMX"
description = "Groovy y Grails en tu idioma"
baseurl = "http://groovyando.org"
languageCode = "es-MX"
title = "Groovyando"
theme = "vito"

[params]
  languageCode = "es-mx"
  forkGitHubUrl = "https://github.com/groovyando/website"
  tagline = "Difundiendo el universo Groovy en tu lenguaje"
  github = "Groovyando"
  slack = "http://slack.groovyando.org"
  twitter = "Groovyando"
  #facebook = "https://www.facebook.com/groups/155793886960/"
  #vimeo = "springhispano"
  #googleplus = "https://plus.google.com/u/5/communities/102613290119984013640"
  #disqusShortname = "groovyando"
  GoogleAnaliticsId = "UA-61658224-1"
  about = "¡Hola! Esta es la comunidad que difunde Groovy y su ecosistema en Español."
  copyrightYear = "2008-2015"
  copyrightOwner = "Domingo Suarez Torres"
  licenseURL = "http://creativecommons.org/licenses/by/3.0/"
  licenseName = "Creative Commons Attribution"
  licenseCaption = "Some rights reserved"


[indexes]
    category = "categories"
    tag = "tags"

[[menu.main]]
    name = "Home"
    identifier = "home"
    url = "/"

[[menu.main]]
  name = "Articles"
  identifier = "articles"
  url = "/article"
  weight = 1